version: "3"
services:

  transpiler:
    build: .
    volumes:
      - .:/app
    command: tsc --w

  api:
    build: .
    depends_on:
      - db
    ports:
      - "0.0.0.0:4000:4000"
    volumes:
      - ./dist:/app
      - ./node_modules/:/app/node_modules
    command: nodemon -L ./main.js

  db:
    image: postgres:alpine
    ports:
      - "0.0.0.0:5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./db.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: "Admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "application"

  linter:
    build: .
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    command: nodemon --delay 500ms -L --exec "find . -path ./ -prune -o -path ./node_modules -prune -o -path ./dist -prune -o -name '*.ts' -print | xargs tslint"

  jest:
    build: .
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    command: jest --coverage --runInBand --watchAll
    environment:
      NODE_ENV: 'test'
