version: "3"
services:

  transpiler:
    build: .
    volumes:
      - .:/app:cached
    command: tsc --w

  api:
    build: .
    ports:
      - "0.0.0.0:4000:4000"
    volumes:
      - ./:/app:cached
    command: nodemon -L dist/main.js
    environment:
      PORT: 4000
      LOG_LEVEL: "debug"
      POSTGRES_HOST: db
      POSTGRES_PORT: "5432"
      POSTGRES_USER: "Admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "application"

  #db:
  #  image: postgres:alpine
  #  ports:
  #    - "0.0.0.0:5432:5432"
  #  volumes:
  #    - ./data/postgres:/var/lib/postgresql/data:cached
  #    - ./db.sql:/docker-entrypoint-initdb.d/init.sql
  #  environment:
  #    POSTGRES_USER: "Admin"
  #    POSTGRES_PASSWORD: "admin"
  #    POSTGRES_DB: "application"

  linter:
    build: .
    volumes:
      - .:/app:cached
    command: "nodemon --watch src/main.ts --exec \"eslint src/**/*.ts ; exit 0\""

  #jest:
  #  build: .
  #  volumes:
  #  - .:/app:cached
  #  command: jest --coverage --runInBand --watchAll
  #  environment:
  #    NODE_ENV: 'test'
  #    PORT: '80'
